# create a numpy array with random number

In [1]:
 # functions that can be used: rand(), randn(), ranf(), randint()

In [2]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.96733081 0.83728938 0.52580018 0.22449612]


In [3]:
var1 = np.random.rand(2,5)
print(var1)

[[0.18951967 0.16498088 0.25197433 0.60246085 0.39723343]
 [0.47922588 0.65285349 0.16852016 0.58974296 0.23026501]]


In [4]:
# randn() used for no close to zero can be positive or negative

In [5]:
var2 = np.random.randn(4)
print(var2)

[-0.04686271  2.48162812 -0.25070608  0.88873999]


In [6]:
# ranf() for getting no between 0 and 1 excluding 1

In [7]:
var3 = np.random.ranf(4)
print(var3)

[0.64378318 0.30441643 0.98201129 0.8948187 ]


In [8]:
# randint()


In [9]:
# var4 = np.random.randint(min,max,total)
var4 = np.random.randint(5,20,5)
print(var4)

[12 11  6 13 17]
