## Numpy

- Built in C for speedy computing - scientific and mathematical calculation in Python. Since python's datatype - list was slow.
- Numpy arrays have afixed size at creation, unlike python lists which can grow dynamically.
- changing the size of an ndarray will create a new array and delete the original.
- the elements in a Numpy array are all required to be of the same datatype.
- less coding
- pandas, matplotlib, seaborn, tensorflow, sci-kit, sklearn, spacy, nltk are built on Numpy

### Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# one dimensional - Vector

a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
# 2D - matrix

In [7]:
b = np.array([[1,2,3], [4,5,6]])

In [8]:
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3D - tensor

In [10]:
c = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])

In [11]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
# dtype

In [13]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [14]:
np.array([0,1,2,3], dtype=bool)

array([False,  True,  True,  True])

In [15]:
np.array([0,1,2,3], dtype=complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.random.random((4,4))

array([[0.7177229 , 0.8288772 , 0.00324554, 0.13358979],
       [0.32064102, 0.13828037, 0.32230483, 0.96918774],
       [0.34096925, 0.54105549, 0.13746145, 0.77707607],
       [0.93396013, 0.12916918, 0.05106888, 0.27001767]])

In [23]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [24]:
np.linspace(10,30,10, dtype = int)

array([10, 12, 14, 16, 18, 21, 23, 25, 27, 30])

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [27]:
# 4D array
np.arange(16, dtype= float).reshape(2,2,2,2)

array([[[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]]],


       [[[ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.]]]])

In [28]:
a3 = np.arange(16, dtype=float).reshape(2,2,2,2)

In [29]:
a3.size

16

In [30]:
a3.itemsize

8

In [31]:
a3.ndim

4

In [32]:
b.ndim

2

In [33]:
a3.shape

(2, 2, 2, 2)

In [34]:
b.shape

(2, 3)

In [35]:
a.shape

(3,)

In [36]:
a.size

3

In [37]:
b.size

6

In [38]:
a.itemsize

4

In [39]:
b.itemsize

4

In [40]:
a.dtype

dtype('int32')

In [41]:
a3.dtype

dtype('float64')

In [42]:
a3.astype(np.int32)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [43]:
a3.dtype

dtype('float64')

In [44]:
## Scalar operations

In [45]:
a

array([1, 2, 3])

In [46]:
a * 4

array([ 4,  8, 12])

In [47]:
a ** 4

array([ 1, 16, 81], dtype=int32)

In [48]:
a + 4 

array([5, 6, 7])

In [49]:
a - 1

array([0, 1, 2])

In [50]:
a / 2

array([0.5, 1. , 1.5])

In [51]:
# relational

In [52]:
a == 3

array([False, False,  True])

In [53]:
# vector operations

In [54]:
d = np.array([4,5,6])

In [55]:
a

array([1, 2, 3])

In [56]:
d

array([4, 5, 6])

In [57]:
a + d

array([5, 7, 9])

In [58]:
a * d

array([ 4, 10, 18])

In [59]:
a ** d

array([  1,  32, 729])

In [60]:
a1 = np.random.random((3,3))

In [61]:
a1 = np.round(a1 * 100)

In [62]:
a1

array([[57., 53., 28.],
       [43., 75., 35.],
       [31., 43., 37.]])

In [63]:
np.max(a1)

75.0

In [64]:
np.min(a1)

28.0

In [65]:
np.sum(a1)

402.0

In [66]:
np.prod(a1)

470910520930500.0

In [67]:
np.mean(a1)

44.666666666666664

In [68]:
np.median(a1)

43.0

In [69]:
np.std(a1)

14.0

In [70]:
np.var(a1)

196.0

In [71]:
np.max(a1, axis = 0) # column max value

array([57., 75., 37.])

In [72]:
np.max(a1, axis = 1) # row max value

array([57., 75., 43.])

In [73]:
# dot product

In [74]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12, 24).reshape(4,3)

In [75]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [77]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [78]:
# log and components

In [79]:
np.log(a2)

C:\Users\AMAN\AppData\Local\Temp\ipykernel_800\970536687.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [80]:
np.exp(a3)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [81]:
np.ceil(np.random.random((2,3))* 100)

array([[ 34., 100.,  87.],
       [ 19.,  71.,   3.]])

In [82]:
np.round(np.random.random((2,3))*100)

array([[15.,  3., 23.],
       [54., 98.,  4.]])

In [83]:
np.floor(np.random.random((2,3))*100)

array([[33., 14., 54.],
       [46., 35., 13.]])

In [84]:
# indexing and slicing

In [85]:
a1 = np.arange(10)                # 1D
a2 = np.arange(12).reshape(3,4)   # 2D
a3 = np.arange(8).reshape(2,2,2)  # 3D

In [86]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a1[2:5]

array([2, 3, 4])

In [88]:
a1[2:7:2]

array([2, 4, 6])

In [89]:
a1[2:7:-2]

array([], dtype=int32)

In [90]:
a1[-2] # value at second last position

8

In [91]:
a1[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [92]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a2[:2, 1::2]

array([[1, 3],
       [5, 7]])

In [94]:
a2[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [95]:
a2[1, ::3]

array([4, 7])

In [96]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [97]:
a2[::2,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [98]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [99]:
a2[:,::3]   # first column and last column

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [100]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [101]:
a2[0:2, 2:]

array([[2, 3],
       [6, 7]])

In [102]:
a2[1:, :2]

array([[4, 5],
       [8, 9]])

In [103]:
a2[:, 2]

array([ 2,  6, 10])

In [104]:
a2[2,:]

array([ 8,  9, 10, 11])

In [105]:
a2[0,:]

array([0, 1, 2, 3])

In [106]:
a2[1,2]

6

In [107]:
a2[2,3]

11

In [108]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [109]:
a3[1,0,1] # locate 5

5

In [110]:
a3[0,0,0] # locate 0

0

In [111]:
a3[1,1,0]

6

In [112]:
a1[-1]

9

In [113]:
a1[0]

0

In [114]:
d = np.arange(27).reshape(3,3,3)

In [115]:
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
for i in np.nditer(d):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [117]:
d[:, 1, 1]

array([ 4, 13, 22])

In [118]:
d[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [119]:
d[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [120]:
d[1,1,1]

13

In [121]:
d[1,:,1]

array([10, 13, 16])

In [122]:
d[0,1]

array([3, 4, 5])

In [123]:
d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [124]:
d[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
num=[3,1,-6,4,-1,5]
print(num.reverse())

None


In [126]:
num[:-1]

[5, -1, 4, -6, 1]

In [127]:
# Iterating

In [128]:
a = np.arange(10)

In [129]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [131]:
b = np.arange(12).reshape(3,4)

In [132]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
for i in b :
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [134]:
for i in b:
    print(b[0])

[0 1 2 3]
[0 1 2 3]
[0 1 2 3]


In [135]:
for i in np.nditer(b):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [136]:
# Transpose

In [137]:
b1 = np.arange(12).reshape(2,6)

In [138]:
b1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [139]:
b1.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [140]:
np.transpose(b1)

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [141]:
# Ravel - converts to 1D array

In [142]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [143]:
d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [144]:
# Stacking

In [145]:
# horizontal stacking

In [146]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)

In [147]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [149]:
np.hstack((a,b, a))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [150]:
# vertical stacking

In [151]:
np.vstack((a,b, a))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
# Splitting

In [153]:
# Horizontal splitting

In [154]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [156]:
# Vertical splitting

In [157]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
np.vsplit(a,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]